### ISSUE TITLE
Wrapper for Authorization Policy Server

### ISSUE THREAD

**Issue by Abrom8** [OceanProtocolEnterprise/research#4]
- [ ] planning of a new wrapper for Authorization Policy Server (supporting SSI in the first iteration, but open for other solutions, e.g. keycloak)

Alex's comment:  This is just design, actual implementation will be handled in a new epic

**Comment by alexcos20** [comment]
Needs a discussion to sync with ocean-node

**Comment by MBadea17** [comment]
The wrapper for the Policy Server was implemented in Ocean Node in this [PR](https://github.com/oceanprotocol/ocean-node/pull/694)
